# Generated by Django 5.0.6 on 2024-05-17 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_invoice_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitem',
            name='idate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
