# Generated by Django 5.0.6 on 2024-05-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_supplierinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasevoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierid', models.CharField(max_length=255)),
                ('suppliername', models.CharField(max_length=255)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='purchaseitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('itemid', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purvoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchasevoc')),
            ],
        ),
    ]
