# Generated by Django 5.0.6 on 2024-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_purchasevoc_purchaseitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_heading',
            name='desc1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice_heading',
            name='desc2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice_heading',
            name='desc3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice_heading',
            name='desc4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
